### ISSUE TITLE
ResultSet populate does not exists in the described signature

### ISSUE THREAD

**Issue by RVDHOFAUDEV** [BasisHub/components#119]
Please notice the email from Ralf van den Heuvel to David Amore on 2019-01-28 ca. 16:15 - thx.

you got 2x ResultSet objects.

do

resu2!.populate(resu1!,Boolean.TRUE)

... ERR 252

**Comment by DaAmore** [comment]
As written in the Email this method is not ment to merge two resultset. It's met to get a basiscomponents Resultset from a java.sql.ResultSet
