### ISSUE TITLE
Split ResultSet::fromJson 

### ISSUE THREAD

**Issue by DaAmore** [BasisHub/components#154]
Rewrite the ResultSet::fromJson to split the json String and call DataRow::fromJson and DataField::fromJson, so we have smaller, easer to maintain methods. You might consider using Helper classes, with static methods to extract the code out of the Classes, so they become more of a Data holding class.

**Comment by DaAmore** [comment]
@Frank-en-stein

**Comment by Frank-en-stein** [comment]
Should I edit the commit message to automatically close this issue?

**Comment by DaAmore** [comment]
It's ok, I close it
