### ISSUE TITLE
bridge: make character set configurable

### ISSUE THREAD

**Issue by StephanWald** [BasisHub/components#64]
currently the bridge assumes UTF.8 for the character encoding. Make this configurable in the 

new String(request!,"UTF-8") 

in an STBL in the config.

SET BRIDGECHARSET=windows-1252

for the internal one use INFO(1,2)

**Comment by vkolarov** [comment]
There is a configuration option for jetty in BBj.properties:

com.basis.server.jetty.servlet.encoding=ISO-8859-15

Is this considered in the bbjsp servlet?

**Comment by StephanWald** [comment]
obsolete - reopen in the bridge plug-in if needed
