### ISSUE TITLE
Get the final "sql statement" prepared and executed by the SqlQueryBC/ SqlTableBC

### ISSUE THREAD

**Issue by StephanWald** [BasisHub/components#69]
I have short request,

Is it possible to ask for the last final "sql statement" prepared and executed by the SqlQueryBC/ SqlTableBC when we execute "retrieve()" method.

Something like "SqlQueryBC!.getSql()"

Sometimes it happens that there is some problem in the "sql text" or the passed parameters not easy to identified.
This will help us in debug purpose.

Regards,
Krishna

**Comment by KrishnaChavan** [comment]
Also, If possible this can be extended for "SqlTableBC.write" method.

**Comment by vkolarov** [comment]
SQL logging can be activated and deactivated in the Enterprise Manager (without restarting the BBjServices).
"Partial Optimization" - shows executed sql statement
"Complete Optimization" - shows more detailed informations (f.g. values in prepared statements)

![2017-12-20_10-34-16](https://user-images.githubusercontent.com/4814082/34200478-88f69e24-e571-11e7-8f64-9988d553bc83.png)

**Comment by KrishnaChavan** [comment]
Veselin,

Looking in to sqlengine logs makes sense when we debug on the system.

I would need it from CarITDMS as a package perspective. CarIT has its own error handling and reporting routines, we send the detailed error report to the carit support when an error occurs. 

I am not sure how we can get the last failed sql from running BBj process. Reading the sqlengine log for the failed query would be not so easy also in first place it has to be enabled by default on the customer systems.

Regards,
Krishna

**Comment by DaAmore** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Get the final "sql statement" prepared and executed by the SqlQueryBC/ SqlTableBC #69](https://trello.com/c/pEG5TiAi/1-get-the-final-sql-statement-prepared-and-executed-by-the-sqlquerybc-sqltablebc-69)

**Comment by DaAmore** [comment]
@KrishnaChavan Maybe you can have a look at the pull request #73 too. If you need something else/something more, just let me know.
