### ISSUE TITLE
Add functions to prepare ResultSet Data for direct population of list controls

### ISSUE THREAD

**Issue by StephanWald** [BasisHub/components#79]
Add a function for ResultSet (probably: introduce a new package for future ui helpers, with static methods) with the following signatures

getFieldValuesAsList(ResultSet rs, String columnName)
getFieldValuesAsList(ResultSet rs, String columnName, Boolean f_addEmptyRow)
getFieldValuesAsList(ResultSet rs, String columnName, Boolean f_addEmptyRow, char cDelimiter)

f_addEmptyRow defaults to FALSE, cDelimiter defaults to 0x0A ( \n )

**Comment by DaAmore** [comment]
The signatures are really likely to be misunderstood, because if it's called `getFieldValuesAsList`, I would expect a `java.util.List` to be returned. But given the parameters it seems like it should produce a String. Can you add some context to clarify the use case?

**Comment by StephanWald** [comment]
We like to server https://documentation.basis.com/BASISHelp/WebHelp/winmethods/bbjlistbutton_insertitems.htm which takes a BBjVector (which is a Java List internally) or a LF-separated String. We can go for the Java List as a return type.

**Comment by DaAmore** [comment]
So I would suggest the following three Methods:
``` Java
public static List<String> getFieldValuesAsList(ResultSet rs, String columnName);
public static List<String> getFieldValuesAsList(ResultSet rs, String columnName, boolean addEmptyRow) ;
public static String getFieldValuesListAsString(List<String> list, String delimiter);
```

**Comment by DaAmore** [comment]
@StephanWald see pull request #83, if it's ok
