### ISSUE TITLE
setAttribute using column name

### ISSUE THREAD

**Issue by hyyan** [BasisHub/components#80]
Currently, it is not possible to set the ResultSet Attributes using the column name, we need to define the column number/index in the DB in order to make it works.
The problem arises when an app is rendering only some columns 

The following is from the [BBjGridExWidget](https://github.com/BBj-Plugins/BBjGridExWidget) project 

```java
    declare SqlQueryBC sbc!
    sbc! = new SqlQueryBC(BBjAPI().getJDBCConnection("CDStore"))
    rs! = sbc!.retrieve("SELECT  * FROM CDINVENTORY")
    
    grid!.addColumn("CDNUMBER","Item#")
    grid!.addColumn("PLAYINGTIME","Playing Time (min)")
    grid!.addColumn("ARTIST","Artist Name")
    grid!.addColumn("TITLE","Record Title")
    grid!.addColumn("LABEL","Publisher")


    // 4 is the index of `PLAYINGTIME` column in `CDINVENTORY` table 
    // but the index of `PLAYINGTIME` in the grid is `2`
    rs!.setAttribute(4 , "Foo","Foo") 
```

You can see how confusing it is to work with this 
The solution would be as easy as adding an overloaded method for `setAttribute` where the first param is a string and under the hood, the method uses [getColumnIndex](https://github.com/BasisHub/components/blob/master/src/main/java/com/basiscomponents/db/ResultSet.java#L559) to get the column index.
Off course the same should apply for `getAttribute` method

**Comment by DaAmore** [comment]
@StephanWald sounds good to me, we should consider to add it to the 18.0 scope
